from django.db import migrations

def insert_exercises(apps, schema_editor):
    ExerciseSuggestion = apps.get_model('fitness', 'ExerciseSuggestion')
    ExerciseSuggestion.objects.bulk_create([
        
    ExerciseSuggestion(goal='fat_loss', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Jumping Jacks', duration=10, calories_burned=70),
    ExerciseSuggestion(goal='fat_loss', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Mountain Climbers', duration=15, calories_burned=110),
    ExerciseSuggestion(goal='fat_loss', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Burpees', duration=20, calories_burned=150),
    ExerciseSuggestion(goal='fat_loss', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Running', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fat_loss', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Jumping Jacks', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fat_loss', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Mountain Climbers', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fat_loss', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Burpees', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fat_loss', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Running', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fat_loss', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Jumping Jacks', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fat_loss', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Mountain Climbers', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fat_loss', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Burpees', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fat_loss', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Running', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fat_loss', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Jumping Jacks', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fat_loss', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Mountain Climbers', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fat_loss', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Burpees', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fat_loss', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Running', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fat_loss', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Jumping Jacks', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fat_loss', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Mountain Climbers', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fat_loss', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Burpees', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fat_loss', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Running', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fat_loss', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Jumping Jacks', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fat_loss', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Mountain Climbers', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fat_loss', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Burpees', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fat_loss', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Running', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fat_loss', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Jumping Jacks', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fat_loss', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Mountain Climbers', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fat_loss', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Burpees', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fat_loss', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Running', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fat_loss', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Jumping Jacks', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fat_loss', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Mountain Climbers', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fat_loss', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Burpees', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fat_loss', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Running', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fat_loss', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Jumping Jacks', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fat_loss', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Mountain Climbers', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fat_loss', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Burpees', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fat_loss', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Running', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fat_loss', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Jumping Jacks', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fat_loss', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Mountain Climbers', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fat_loss', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Burpees', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fat_loss', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Running', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fat_loss', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Jumping Jacks', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fat_loss', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Mountain Climbers', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fat_loss', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Burpees', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fat_loss', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Running', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fat_loss', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Jumping Jacks', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fat_loss', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Mountain Climbers', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fat_loss', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Burpees', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fat_loss', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Running', duration=25, calories_burned=190),
ExerciseSuggestion(goal='muscle_gain', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Deadlifts', duration=10, calories_burned=70),
ExerciseSuggestion(goal='muscle_gain', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Bench Press', duration=15, calories_burned=110),
ExerciseSuggestion(goal='muscle_gain', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Pull-Ups', duration=20, calories_burned=150),
ExerciseSuggestion(goal='muscle_gain', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Lunges', duration=25, calories_burned=190),
ExerciseSuggestion(goal='muscle_gain', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Deadlifts', duration=10, calories_burned=70),
ExerciseSuggestion(goal='muscle_gain', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Bench Press', duration=15, calories_burned=110),
ExerciseSuggestion(goal='muscle_gain', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Pull-Ups', duration=20, calories_burned=150),
ExerciseSuggestion(goal='muscle_gain', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Lunges', duration=25, calories_burned=190),
ExerciseSuggestion(goal='muscle_gain', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Deadlifts', duration=10, calories_burned=70),
ExerciseSuggestion(goal='muscle_gain', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Bench Press', duration=15, calories_burned=110),
ExerciseSuggestion(goal='muscle_gain', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Pull-Ups', duration=20, calories_burned=150),
ExerciseSuggestion(goal='muscle_gain', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Lunges', duration=25, calories_burned=190),
ExerciseSuggestion(goal='muscle_gain', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Deadlifts', duration=10, calories_burned=70),
ExerciseSuggestion(goal='muscle_gain', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Bench Press', duration=15, calories_burned=110),
ExerciseSuggestion(goal='muscle_gain', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Pull-Ups', duration=20, calories_burned=150),
ExerciseSuggestion(goal='muscle_gain', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Lunges', duration=25, calories_burned=190),
ExerciseSuggestion(goal='muscle_gain', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Deadlifts', duration=10, calories_burned=70),
ExerciseSuggestion(goal='muscle_gain', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Bench Press', duration=15, calories_burned=110),
ExerciseSuggestion(goal='muscle_gain', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Pull-Ups', duration=20, calories_burned=150),
ExerciseSuggestion(goal='muscle_gain', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Lunges', duration=25, calories_burned=190),
ExerciseSuggestion(goal='muscle_gain', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Deadlifts', duration=10, calories_burned=70),
ExerciseSuggestion(goal='muscle_gain', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Bench Press', duration=15, calories_burned=110),
ExerciseSuggestion(goal='muscle_gain', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Pull-Ups', duration=20, calories_burned=150),
ExerciseSuggestion(goal='muscle_gain', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Lunges', duration=25, calories_burned=190),
ExerciseSuggestion(goal='muscle_gain', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Deadlifts', duration=10, calories_burned=70),
ExerciseSuggestion(goal='muscle_gain', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Bench Press', duration=15, calories_burned=110),
ExerciseSuggestion(goal='muscle_gain', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Pull-Ups', duration=20, calories_burned=150),
ExerciseSuggestion(goal='muscle_gain', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Lunges', duration=25, calories_burned=190),
ExerciseSuggestion(goal='muscle_gain', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Deadlifts', duration=10, calories_burned=70),
ExerciseSuggestion(goal='muscle_gain', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Bench Press', duration=15, calories_burned=110),
ExerciseSuggestion(goal='muscle_gain', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Pull-Ups', duration=20, calories_burned=150),
ExerciseSuggestion(goal='muscle_gain', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Lunges', duration=25, calories_burned=190),
ExerciseSuggestion(goal='muscle_gain', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Deadlifts', duration=10, calories_burned=70),
ExerciseSuggestion(goal='muscle_gain', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Bench Press', duration=15, calories_burned=110),
ExerciseSuggestion(goal='muscle_gain', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Pull-Ups', duration=20, calories_burned=150),
ExerciseSuggestion(goal='muscle_gain', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Lunges', duration=25, calories_burned=190),
ExerciseSuggestion(goal='muscle_gain', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Deadlifts', duration=10, calories_burned=70),
ExerciseSuggestion(goal='muscle_gain', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Bench Press', duration=15, calories_burned=110),
ExerciseSuggestion(goal='muscle_gain', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Pull-Ups', duration=20, calories_burned=150),
ExerciseSuggestion(goal='muscle_gain', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Lunges', duration=25, calories_burned=190),
ExerciseSuggestion(goal='muscle_gain', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Deadlifts', duration=10, calories_burned=70),
ExerciseSuggestion(goal='muscle_gain', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Bench Press', duration=15, calories_burned=110),
ExerciseSuggestion(goal='muscle_gain', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Pull-Ups', duration=20, calories_burned=150),
ExerciseSuggestion(goal='muscle_gain', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Lunges', duration=25, calories_burned=190),
ExerciseSuggestion(goal='muscle_gain', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Deadlifts', duration=10, calories_burned=70),
ExerciseSuggestion(goal='muscle_gain', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Bench Press', duration=15, calories_burned=110),
ExerciseSuggestion(goal='muscle_gain', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Pull-Ups', duration=20, calories_burned=150),
ExerciseSuggestion(goal='muscle_gain', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Lunges', duration=25, calories_burned=190),
ExerciseSuggestion(goal='endurance', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Cycling', duration=10, calories_burned=70),
ExerciseSuggestion(goal='endurance', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Swimming', duration=15, calories_burned=110),
ExerciseSuggestion(goal='endurance', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Rowing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='endurance', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Hiking', duration=25, calories_burned=190),
ExerciseSuggestion(goal='endurance', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Cycling', duration=10, calories_burned=70),
ExerciseSuggestion(goal='endurance', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Swimming', duration=15, calories_burned=110),
ExerciseSuggestion(goal='endurance', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Rowing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='endurance', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Hiking', duration=25, calories_burned=190),
ExerciseSuggestion(goal='endurance', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Cycling', duration=10, calories_burned=70),
ExerciseSuggestion(goal='endurance', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Swimming', duration=15, calories_burned=110),
ExerciseSuggestion(goal='endurance', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Rowing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='endurance', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Hiking', duration=25, calories_burned=190),
ExerciseSuggestion(goal='endurance', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Cycling', duration=10, calories_burned=70),
ExerciseSuggestion(goal='endurance', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Swimming', duration=15, calories_burned=110),
ExerciseSuggestion(goal='endurance', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Rowing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='endurance', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Hiking', duration=25, calories_burned=190),
ExerciseSuggestion(goal='endurance', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Cycling', duration=10, calories_burned=70),
ExerciseSuggestion(goal='endurance', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Swimming', duration=15, calories_burned=110),
ExerciseSuggestion(goal='endurance', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Rowing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='endurance', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Hiking', duration=25, calories_burned=190),
ExerciseSuggestion(goal='endurance', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Cycling', duration=10, calories_burned=70),
ExerciseSuggestion(goal='endurance', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Swimming', duration=15, calories_burned=110),
ExerciseSuggestion(goal='endurance', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Rowing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='endurance', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Hiking', duration=25, calories_burned=190),
ExerciseSuggestion(goal='endurance', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Cycling', duration=10, calories_burned=70),
ExerciseSuggestion(goal='endurance', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Swimming', duration=15, calories_burned=110),
ExerciseSuggestion(goal='endurance', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Rowing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='endurance', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Hiking', duration=25, calories_burned=190),
ExerciseSuggestion(goal='endurance', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Cycling', duration=10, calories_burned=70),
ExerciseSuggestion(goal='endurance', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Swimming', duration=15, calories_burned=110),
ExerciseSuggestion(goal='endurance', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Rowing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='endurance', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Hiking', duration=25, calories_burned=190),
ExerciseSuggestion(goal='endurance', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Cycling', duration=10, calories_burned=70),
ExerciseSuggestion(goal='endurance', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Swimming', duration=15, calories_burned=110),
ExerciseSuggestion(goal='endurance', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Rowing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='endurance', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Hiking', duration=25, calories_burned=190),
ExerciseSuggestion(goal='endurance', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Cycling', duration=10, calories_burned=70),
ExerciseSuggestion(goal='endurance', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Swimming', duration=15, calories_burned=110),
ExerciseSuggestion(goal='endurance', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Rowing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='endurance', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Hiking', duration=25, calories_burned=190),
ExerciseSuggestion(goal='endurance', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Cycling', duration=10, calories_burned=70),
ExerciseSuggestion(goal='endurance', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Swimming', duration=15, calories_burned=110),
ExerciseSuggestion(goal='endurance', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Rowing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='endurance', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Hiking', duration=25, calories_burned=190),
ExerciseSuggestion(goal='endurance', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Cycling', duration=10, calories_burned=70),
ExerciseSuggestion(goal='endurance', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Swimming', duration=15, calories_burned=110),
ExerciseSuggestion(goal='endurance', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Rowing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='endurance', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Hiking', duration=25, calories_burned=190),
ExerciseSuggestion(goal='flexibility', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Yoga Flow', duration=10, calories_burned=70),
ExerciseSuggestion(goal='flexibility', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Static Stretching', duration=15, calories_burned=110),
ExerciseSuggestion(goal='flexibility', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Dynamic Warm-Up', duration=20, calories_burned=150),
ExerciseSuggestion(goal='flexibility', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Pilates', duration=25, calories_burned=190),
ExerciseSuggestion(goal='flexibility', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Yoga Flow', duration=10, calories_burned=70),
ExerciseSuggestion(goal='flexibility', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Static Stretching', duration=15, calories_burned=110),
ExerciseSuggestion(goal='flexibility', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Dynamic Warm-Up', duration=20, calories_burned=150),
ExerciseSuggestion(goal='flexibility', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Pilates', duration=25, calories_burned=190),
ExerciseSuggestion(goal='flexibility', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Yoga Flow', duration=10, calories_burned=70),
ExerciseSuggestion(goal='flexibility', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Static Stretching', duration=15, calories_burned=110),
ExerciseSuggestion(goal='flexibility', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Dynamic Warm-Up', duration=20, calories_burned=150),
ExerciseSuggestion(goal='flexibility', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Pilates', duration=25, calories_burned=190),
ExerciseSuggestion(goal='flexibility', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Yoga Flow', duration=10, calories_burned=70),
ExerciseSuggestion(goal='flexibility', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Static Stretching', duration=15, calories_burned=110),
ExerciseSuggestion(goal='flexibility', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Dynamic Warm-Up', duration=20, calories_burned=150),
ExerciseSuggestion(goal='flexibility', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Pilates', duration=25, calories_burned=190),
ExerciseSuggestion(goal='flexibility', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Yoga Flow', duration=10, calories_burned=70),
ExerciseSuggestion(goal='flexibility', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Static Stretching', duration=15, calories_burned=110),
ExerciseSuggestion(goal='flexibility', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Dynamic Warm-Up', duration=20, calories_burned=150),
ExerciseSuggestion(goal='flexibility', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Pilates', duration=25, calories_burned=190),
ExerciseSuggestion(goal='flexibility', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Yoga Flow', duration=10, calories_burned=70),
ExerciseSuggestion(goal='flexibility', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Static Stretching', duration=15, calories_burned=110),
ExerciseSuggestion(goal='flexibility', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Dynamic Warm-Up', duration=20, calories_burned=150),
ExerciseSuggestion(goal='flexibility', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Pilates', duration=25, calories_burned=190),
ExerciseSuggestion(goal='flexibility', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Yoga Flow', duration=10, calories_burned=70),
ExerciseSuggestion(goal='flexibility', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Static Stretching', duration=15, calories_burned=110),
ExerciseSuggestion(goal='flexibility', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Dynamic Warm-Up', duration=20, calories_burned=150),
ExerciseSuggestion(goal='flexibility', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Pilates', duration=25, calories_burned=190),
ExerciseSuggestion(goal='flexibility', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Yoga Flow', duration=10, calories_burned=70),
ExerciseSuggestion(goal='flexibility', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Static Stretching', duration=15, calories_burned=110),
ExerciseSuggestion(goal='flexibility', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Dynamic Warm-Up', duration=20, calories_burned=150),
ExerciseSuggestion(goal='flexibility', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Pilates', duration=25, calories_burned=190),
ExerciseSuggestion(goal='flexibility', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Yoga Flow', duration=10, calories_burned=70),
ExerciseSuggestion(goal='flexibility', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Static Stretching', duration=15, calories_burned=110),
ExerciseSuggestion(goal='flexibility', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Dynamic Warm-Up', duration=20, calories_burned=150),
ExerciseSuggestion(goal='flexibility', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Pilates', duration=25, calories_burned=190),
ExerciseSuggestion(goal='flexibility', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Yoga Flow', duration=10, calories_burned=70),
ExerciseSuggestion(goal='flexibility', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Static Stretching', duration=15, calories_burned=110),
ExerciseSuggestion(goal='flexibility', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Dynamic Warm-Up', duration=20, calories_burned=150),
ExerciseSuggestion(goal='flexibility', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Pilates', duration=25, calories_burned=190),
ExerciseSuggestion(goal='flexibility', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Yoga Flow', duration=10, calories_burned=70),
ExerciseSuggestion(goal='flexibility', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Static Stretching', duration=15, calories_burned=110),
ExerciseSuggestion(goal='flexibility', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Dynamic Warm-Up', duration=20, calories_burned=150),
ExerciseSuggestion(goal='flexibility', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Pilates', duration=25, calories_burned=190),
ExerciseSuggestion(goal='flexibility', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Yoga Flow', duration=10, calories_burned=70),
ExerciseSuggestion(goal='flexibility', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Static Stretching', duration=15, calories_burned=110),
ExerciseSuggestion(goal='flexibility', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Dynamic Warm-Up', duration=20, calories_burned=150),
ExerciseSuggestion(goal='flexibility', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Pilates', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fitness', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Jump Rope', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fitness', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Shadow Boxing', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fitness', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Stair Climbing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fitness', level='beginner', bmi_min=16.0, bmi_max=18.4, name='Jump Squats', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fitness', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Jump Rope', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fitness', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Shadow Boxing', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fitness', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Stair Climbing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fitness', level='beginner', bmi_min=18.5, bmi_max=24.9, name='Jump Squats', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fitness', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Jump Rope', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fitness', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Shadow Boxing', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fitness', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Stair Climbing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fitness', level='beginner', bmi_min=25.0, bmi_max=29.9, name='Jump Squats', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fitness', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Jump Rope', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fitness', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Shadow Boxing', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fitness', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Stair Climbing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fitness', level='beginner', bmi_min=30.0, bmi_max=34.9, name='Jump Squats', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fitness', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Jump Rope', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fitness', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Shadow Boxing', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fitness', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Stair Climbing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fitness', level='intermediate', bmi_min=16.0, bmi_max=18.4, name='Jump Squats', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fitness', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Jump Rope', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fitness', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Shadow Boxing', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fitness', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Stair Climbing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fitness', level='intermediate', bmi_min=18.5, bmi_max=24.9, name='Jump Squats', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fitness', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Jump Rope', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fitness', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Shadow Boxing', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fitness', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Stair Climbing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fitness', level='intermediate', bmi_min=25.0, bmi_max=29.9, name='Jump Squats', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fitness', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Jump Rope', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fitness', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Shadow Boxing', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fitness', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Stair Climbing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fitness', level='intermediate', bmi_min=30.0, bmi_max=34.9, name='Jump Squats', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fitness', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Jump Rope', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fitness', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Shadow Boxing', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fitness', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Stair Climbing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fitness', level='advanced', bmi_min=16.0, bmi_max=18.4, name='Jump Squats', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fitness', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Jump Rope', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fitness', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Shadow Boxing', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fitness', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Stair Climbing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fitness', level='advanced', bmi_min=18.5, bmi_max=24.9, name='Jump Squats', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fitness', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Jump Rope', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fitness', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Shadow Boxing', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fitness', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Stair Climbing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fitness', level='advanced', bmi_min=25.0, bmi_max=29.9, name='Jump Squats', duration=25, calories_burned=190),
ExerciseSuggestion(goal='fitness', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Jump Rope', duration=10, calories_burned=70),
ExerciseSuggestion(goal='fitness', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Shadow Boxing', duration=15, calories_burned=110),
ExerciseSuggestion(goal='fitness', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Stair Climbing', duration=20, calories_burned=150),
ExerciseSuggestion(goal='fitness', level='advanced', bmi_min=30.0, bmi_max=34.9, name='Jump Squats', duration=25, calories_burned=190),


        
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),  # hoặc tên migration đầu tiên của bạn
    ]

    operations = [
        migrations.RunPython(insert_exercises),
    ]
