# Generated by Django 5.2 on 2025-05-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('energy', 'Improve Energy')], max_length=20)),
                ('bmi_min', models.FloatField()),
                ('bmi_max', models.FloatField()),
                ('calories', models.PositiveIntegerField()),
                ('carbs', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField()),
                ('fat', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='suggestedmeal',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='suggestedmealplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='weightlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='NutritionEntry',
        ),
        migrations.DeleteModel(
            name='SuggestedMeal',
        ),
        migrations.DeleteModel(
            name='SuggestedMealPlan',
        ),
        migrations.DeleteModel(
            name='UserGoal',
        ),
        migrations.DeleteModel(
            name='WeightLog',
        ),
    ]
