# Generated by Django 5.2 on 2025-05-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_savedmealplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('energy', 'Improve Energy')], max_length=20)),
                ('bmi_min', models.FloatField()),
                ('bmi_max', models.FloatField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10)),
                ('meal_name', models.CharField(max_length=100)),
                ('calories', models.PositiveIntegerField()),
                ('carbs', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField()),
                ('fat', models.PositiveIntegerField()),
            ],
        ),
    ]
