# Generated by Django 5.2 on 2025-05-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_foodentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodentry',
            old_name='food_item',
            new_name='food_name',
        ),
    ]
